# fly.toml for FastAPI service (private to internal network)
app = "fastapiservice245"
primary_region = "bom"

[build]

[http_service]
  internal_port = 8000
  internal = true          # 👈 Makes it private (no public internet access)
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"       # For heavier ML workloads, consider "performance"
  cpus = 1

command = ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]